apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workshop-data-pvc
  namespace: workshop
  labels:
    app: workshop-storage
spec:
  # ใช้ StorageClass default ของ cluster
  # k3d/kind/minikube มี default StorageClass อยู่แล้ว (dynamic provisioning)
  accessModes:
  - ReadWriteOnce                   # mount ได้ครั้งละ 1 node
  resources:
    requests:
      storage: 1Gi                  # ขอ storage 1GB
  # storageClassName: "xxx"         # comment ไว้เพื่อใช้ค่า default , สามารถระบุชื่อ StorageClass ได้ที่นี่หากต้องการ
