apiVersion: v1
kind: Secret
metadata:
  name: workshop-web-secret
  namespace: workshop
  labels:
    app: workshop-web
# stringData: ใช้ plain text เพื่อความง่ายในการสอน
# (Kubernetes จะ encode เป็น base64 ให้อัตโนมัติ)
stringData:
  DB_PASSWORD: "s3cur3-p@ssw0rd"
  API_KEY: "workshop-api-key-12345"
