apiVersion: v1
kind: Service
metadata:
  name: workshop-web-headless
  namespace: workshop
  labels:
    app: workshop-stateful
spec:
  # clusterIP: None = Headless Service
  # ไม่มี load balancing, DNS resolve ไปยัง Pod IP โดยตรง
  clusterIP: None
  selector:
    app: workshop-stateful
  ports:
  - name: http
    port: 80
    targetPort: 80
